### ISSUE TITLE
Can I work on the improvement of the UI part as well as the responsiveness of the App

### ISSUE THREAD

**Issue by alok27a** [IEEE-VIT/weatherbes-android#28] opened 2021-10-02 14:53 UTC

**Comment by jazxii** [comment] 2021-10-02 15:32
hey @alok27a , you can work on it and send the PR. But still, If it gets to the point to where the UI in #2 or #11 gets their PR first, we have to merge them as theirs will be top priority as first to PR. Do take your decision considering that.

**Comment by jazxii** [comment] 2021-10-02 15:42
hey @alok27a , sorry but this a duplicate of the issues #11 and #2. Please look for these or other issues. 
Still, If you want to work on this issue, you can. We will be checking it and merge it if its fulfilling the requirements.
Good Luck out there!

**Closed** 2021-10-02 15:43 UTC
Labels: optimization, hacktoberfest, medium
